# -*- coding: utf-8 -*-
"""flordaman.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yYqjywnLVmLGdLjVhPmdiJR5RJ5Y4y4T
"""

import requests
import json
from datetime import datetime
from IPython.display import Markdown, display


def get_florida_man_story(month, day):
    # Get the API key from Colab's userdata
    api_key = userdata.get('PERPLEXITY_API_KEY')

    if not api_key:
        return "Error: Perplexity API key not found. Please set it in Colab's userdata."

    headers = {
        'Authorization': f'Bearer {api_key}',
        'Content-Type': 'application/json'
    }

    query = f"Florida Man {month} {day}"

    data = {
        'model': 'llama-3.1-sonar-large-128k-online',
        'messages': [
            {'role': 'system', 'content': 'You are a humorous assistant. Respond to queries about Florida Man in a funny tone.'},
            {'role': 'user', 'content': f"Tell me a funny Florida Man story that happened on {month} {day}"}
        ]
    }

    response = requests.post('https://api.perplexity.ai/chat/completions', headers=headers, data=json.dumps(data))

    if response.status_code == 200:
        return response.json()['choices'][0]['message']['content']
    else:
        return f"Error: {response.status_code} - {response.text}"

def main():
    print("Welcome to the Florida Man Birthday Story Generator!")

    user_input = input("Enter your birth month and day (e.g., 'January 15'): ")

    date = datetime.strptime(user_input, "%B %d")
    month = date.strftime("%B")
    day = date.strftime("%d")

    print("Searching for your Florida Man story...")
    story = get_florida_man_story(month, day)
    print("\nHere's your Florida Man story:\n")
    display(Markdown(story))
    #print(story)

if __name__ == "__main__":
    main()